jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - artifactory/install
#      - artifactory/configure
#      - run:
#          name: Install JFrog CLI
#          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: configure CLI to Artifactory
          command: |
            ./jfrog config add kushalmadireddy.jfrog.io --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
      - artifactory/build-integration
#            ./jfrog rt u ./target/*.jar <artifactory_repo_name> --build-name=petclinic_circleci --build-number=$CIRCLE_BUILD_NUM
#            ./jfrog rt bce petclinic_circleci $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
#            ./jfrog rt bp petclinic_circleci $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
orbs:
  artifactory: circleci/artifactory@1.0.0
version: 2.1
