jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure
      - artifactory/build-integration
orbs:
  artifactory: circleci/artifactory@1.0.0
version: 2.1
