version: '2.1'
orbs:
  artifactory: circleci/artifactory@1.0.0
workflows:
  simple-docker-example:
    jobs:
      - artifactory/docker-publish:
          docker-registry: kushalmadireddy.jfrog.io
          docker-tag: 'kushalmadireddy.jfrog.io/hello-world:1.0-${CIRCLE_BUILD_NUM}'
          name: Docker Publish Simple
          repository: default-docker-virtual
