version: 2
jobs:
  upload-artifact:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: thisiskushal
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: maven build
          command: |
            mvn clean install
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog config add kushalmadireddy.jfrog.io --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
            ./jfrog rt u ./target/*.jar demo-docker-virtual --build-name=petclinic-circleci --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce petclinic-circleci $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp petclinic-circleci $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
