version: 2.1
orbs:
  artifactory: ware2go/artifactory@1.1.25
jobs:
      build:
        docker:
          - image: cimg/openjdk:17.0.2
        steps:
          - checkout
          - run: mvn clean install
          - artifactory/upload:
              source: target/*.jar
              target: default-maven-virtual